"""
app/schemas/conversation.py

Pydantic models for request/response payloads used by the chat API.
"""
from pydantic import BaseModel, Field
from typing import Literal


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    """Payload for POST /chat"""

    session_id: str = Field(
        ...,
        description="Unique conversation session identifier (UUID or any string).",
        examples=["user-abc-123"],
    )
    query: str = Field(
        ...,
        description="The user's question to the FPT compliance assistant.",
        min_length=1,
        examples=["Tôi có được phép kiêm nhiệm ở công ty khác không?"],
    )


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------

class MessageItem(BaseModel):
    """A single message in the conversation history."""

    role: Literal["human", "ai", "system"]
    content: str


class ChatResponse(BaseModel):
    """Response from POST /chat"""

    session_id: str
    answer: str = Field(description="The final answer generated by the AI agent.")


class HistoryResponse(BaseModel):
    """Response from GET /history/{session_id}"""

    session_id: str
    messages: list[MessageItem]


class DeleteResponse(BaseModel):
    """Response from DELETE /history/{session_id}"""

    session_id: str
    message: str = "History deleted successfully."


# ---------------------------------------------------------------------------
# Conversation list (PostgreSQL-backed)
# ---------------------------------------------------------------------------

class ConversationSummary(BaseModel):
    """One entry in the conversations list."""

    id: str
    title: str
    message_count: int
    created_at: str
    updated_at: str

    model_config = {"from_attributes": True}


class ConversationsListResponse(BaseModel):
    conversations: list[ConversationSummary]
